# Generated by Django 4.1.1 on 2024-10-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminsite', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(blank=True, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
