# Generated by Django 4.1.1 on 2024-10-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminsite', '0006_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='stars',
        ),
    ]
