# Generated by Django 4.1.1 on 2024-10-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminsite', '0007_remove_movie_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='reviews',
            field=models.IntegerField(),
        ),
    ]
