# Generated by Django 4.1.1 on 2024-10-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminsite', '0009_remove_movie_cast_castmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
