# Generated by Django 4.1.1 on 2024-10-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminsite', '0010_alter_movie_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mimage',
            field=models.ImageField(blank=True, upload_to='static/movies/'),
        ),
    ]
